@startuml

title C4 - Nível 2 - Diagrama de Contêiners

top to bottom direction

actor "Cliente" as cliente
actor "Administrador" as adm

rectangle "Sistema de\nGestão de\nChamados" as sistema {
    rectangle "Frontend" as frontend
    rectangle "FastAPI" as fastapi
    rectangle "Service" as service
    rectangle "SQL" as sql
}

' Mantém Cliente e Administrador lado a lado
cliente -[hidden]right- adm

' Relacionamentos
cliente -> sistema : Envia solicitação\ne acompanha status
adm --> sistema : Gerencia o sistema\ne seus recursos

frontend -> fastapi : HTTP / HTTPS
fastapi --> service : comunica
service --> sql : comunica


sistema --> email : Envia e recebe\ne-mails de notificação
sistema -> db : Armazena e\nrecupera dados

@enduml
